#!/bin/sh
#
# Copyright (c) 2008 rPath, Inc.
#
# This program is distributed under the terms of the Common Public License,
# version 1.0. A copy of this license should have been distributed with this
# source file in a file called LICENSE. If it is not present, the license
# is always available at http://www.rpath.com/permanent/licenses/CPL-1.0.
#
# This program is distributed in the hope that it will be useful, but
# without any warranty; without even the implied warranty of merchantability
# or fitness for a particular purpose. See the Common Public License for
# full details.
#

if ! which pylint > /dev/null 2>&1; then
   echo "pylint is not installed"
   exit 0
fi

if [ -x reports ]; then
   rm -rf reports;
fi
mkdir reports
cd reports

if [ -z "$*" ]; then
    files="restlib"
else
    files=$@
fi

PYTHONPATH=`pwd`/.. pylint --init-hook='import sys; sys.path.append("../.."); import init_pylint' --rcfile='../pylintrc' $files
rc=$?
for file in `ls`; do
   if [ ! -s $file ]; then
      rm $file;
   fi
done
exit $rc
